# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'CurlThin.Native/pack_curl_native.py'
    arguments: '--libcurl-version=$(LIBCURL_VER) --openssl-version=$(OPENSSL_VER) --clean'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    feedsToUse: 'select'
    versioningScheme: 'off'
